//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterenaryClinicApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Veterinary_ClinicEntities : DbContext
    {
        public Veterinary_ClinicEntities()
            : base("name=Veterinary_ClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ветеринарные_клиники> Ветеринарные_клиники { get; set; }
        public virtual DbSet<Виды_животных> Виды_животных { get; set; }
        public virtual DbSet<Виды_процедуры> Виды_процедуры { get; set; }
        public virtual DbSet<Владельцы> Владельцы { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Животные> Животные { get; set; }
        public virtual DbSet<Классы_животных> Классы_животных { get; set; }
        public virtual DbSet<Лицензии> Лицензии { get; set; }
        public virtual DbSet<Процедуры> Процедуры { get; set; }
        public virtual DbSet<Районы> Районы { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тип_собственности> Тип_собственности { get; set; }
    }
}
