//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterenaryClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виды_процедуры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Виды_процедуры()
        {
            this.Процедуры = new HashSet<Процедуры>();
        }
    
        public int Код_вида_процедуры { get; set; }
        public string Вид_процедуры { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Процедуры> Процедуры { get; set; }
    }
}
