//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterenaryClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лицензии
    {
        public int Код_лицензии { get; set; }
        public string Лицензия__ { get; set; }
        public System.DateTime Срок_окончания_лицензии { get; set; }
        public byte[] Фото_лицензии { get; set; }
        public int Код_ветеринарной_клинки { get; set; }
    
        public virtual Ветеринарные_клиники Ветеринарные_клиники { get; set; }
    }
}
